from models import TripStatus, User, Item, db
from app import app

db.drop_all()
db.create_all()

TripStatus.query.delete()
Item.query.delete()
User.query.delete()


# Add Trip Statuses

upcoming = TripStatus(status='Upcoming')
completed = TripStatus(status='Completed')
archived = TripStatus(status='Archived')

db.session.add(upcoming)
db.session.add(completed)
db.session.add(archived)
db.session.commit()

defaultUser = User.register(first_name = 'system_user',
last_name = 'system_user',
username = 'system_user',
password = 'user_setup')

db.session.add(defaultUser)
db.session.commit()


Maps = Item(name ='Maps', category = 'Navigation', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Permits = Item(name ='Permits', category = 'Navigation', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Compass = Item(name ='Compass', category = 'Navigation', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Backpack = Item(name ='Backpack', category = 'Gear', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
RainCover = Item(name ='Rain Cover', category = 'Gear', essential = True, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Tent = Item(name ='Tent', category = 'Gear', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Tarp = Item(name ='Tarp', category = 'Gear', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
RainFly = Item(name ='Rain Fly', category = 'Gear', essential = True, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
SleepingBag = Item(name ='Sleeping Bag', category = 'Sleeping', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
SleepingPad = Item(name ='Sleeping Pad', category = 'Sleeping', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
TrekkingPoles = Item(name ='Trekking Poles', category = 'Gear', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
BearCanister = Item(name ='Bear Canister', category = 'Safety', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
WaterFilter = Item(name ='Water Filter/Purifier',category = 'Safety', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = True, emergency_precautionary = True, created_by = 1, removable =False)
Aquatabs = Item(name ='Aquatabs', category = 'Safety', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
HeadLamp = Item(name ='Head Lamp', category = 'Safety', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
ExtraBatteries = Item(name ='Extra Batteries', category = 'Miscellaneous', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
BearSpray = Item(name ='Bear Spray', category = 'Safety', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
BugSpray = Item(name ='Bug Spray', category = 'Miscellaneous', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Knife = Item(name ='Knife', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
MultiTool = Item(name ='Multi-Tool', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Nalgene = Item(name ='Nalgene', category = 'Gear', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
HandSanitizer = Item(name ='Hand Sanitizer', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
ToiletPaper  = Item(name ='Toilet Paper ', category = 'Hygiene', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
SealableBags = Item(name ='Sealable Bags', category = 'Hygiene', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Toothbrush = Item(name ='Toothbrush', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Toolpaste = Item(name ='Toolpaste', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Soap = Item(name ='Soap', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
ContactSolution = Item(name ='Contact Solution', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Deodorant = Item(name ='Deodorant', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
BathroomHandShovel = Item(name ='Bathroom Hand Shovel', category = 'Hygiene', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Food = Item(name ='Food', category = 'Cooking', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
EnergyChews = Item(name ='Energy Chews', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Fuel = Item(name ='Fuel', category = 'Cooking', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Matches = Item(name ='Matches', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
FireStarter = Item(name ='Fire Starter', category = 'Cooking', essential = False, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
FlintSteel = Item(name ='Flint and Steel', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Lint = Item(name ='Lint', category = 'Cooking', essential = False, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Lighter = Item(name ='Lighter', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Stove = Item(name ='Stove', category = 'Cooking', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Cookset = Item(name ='Cookset', category = 'Cooking', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PotGrabber = Item(name ='Pot Grabber', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Bowls = Item(name ='Bowls', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Plates = Item(name ='Plates', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Silverware = Item(name ='Silverware', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Mugs = Item(name ='Mugs', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
DishSoap = Item(name ='Dish Soap', category = 'Cooking', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
FirstAidKit = Item(name ='First-Aid Kit', category = 'Safety', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Garmin = Item(name ='Garmin', category = 'Safety', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
WalkieTalkies = Item(name ='Walkie Talkies', category = 'Safety', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Gauze = Item(name ='Gauze', category = 'Safety', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Wraps = Item(name ='Wraps', category = 'Safety', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
Flashlight = Item(name ='Flashlight', category = 'Safety', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
String = Item(name ='String', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Rope = Item(name ='Rope', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
ReadingMaterial = Item(name ='Reading Material', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PortablePhoneCharger = Item(name ='Portable Phone Charger', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Hatchet = Item(name ='Hatchet', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
SmallTrashBags = Item(name ='Small Trash Bags', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
TentPatchKit = Item(name ='Tent Patch Kit', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
DuctTape = Item(name ='Duct Tape', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
SleepingBagLiner = Item(name ='Sleeping Bag Liner', category = 'Sleeping', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
InflatablePillow = Item(name ='Inflatable Pillow', category = 'Sleeping', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
BugNet = Item(name ='Bug Net', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PlayingCards = Item(name ='Playing Cards', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PetPack = Item(name ='Pet Pack', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PetFood = Item(name ='Pet Food', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Treats = Item(name ='Treats', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
LongLeash = Item(name ='Long Leash', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
ShortLeash = Item(name ='Short Leash', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Harness = Item(name ='Harness', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Comb = Item(name ='Comb', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
AbrasionSpray = Item(name ='Abrasion Spray', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
CollapsibleBowl = Item(name ='Collapsible Bowl', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
LightCollar = Item(name ='Light Collar', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Towel = Item(name ='Towel', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PetSleepingPad = Item(name ='Pet Sleeping Pad', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
PoopBags = Item(name ='Poop Bags', category = 'Pet', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
HandWarmers = Item(name ='Hand Warmers', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
FeetWarmers = Item(name ='Feet Warmers', category = 'Miscellaneous', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = True, created_by = 1, removable =False)
MetalNalgene = Item(name ='Metal Nalgene', category = 'Gear', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Gloves = Item(name ='Gloves', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Hat = Item(name ='Hat', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
LongSleeveShirt = Item(name ='Long Sleeve Shirt', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
QuickDryingPants = Item(name ='Quick Drying Pants', category = 'Clothing', essential = True, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
RainProofPants = Item(name ='Rain Proof Pants', category = 'Clothing', essential = True, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Shorts = Item(name ='Shorts', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = True, emergency_precautionary = False, created_by = 1, removable =False)
Leggings = Item(name ='Leggings', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = True, emergency_precautionary = False, created_by = 1, removable =False)
LightweightFleece = Item(name ='Lightweight Fleece', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
LightweightJacket = Item(name ='Lightweight Jacket', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = True, emergency_precautionary = False, created_by = 1, removable =False)
WoolSocks = Item(name ='Wool Socks', category = 'Clothing', essential = True, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
HikingBoots = Item(name ='Hiking Boots', category = 'Clothing', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
CampSandals = Item(name ='Camp Sandals', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
MoistureWickingShirt = Item(name ='Moisture Wicking Shirt', category = 'Clothing', essential = True, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
Underwear = Item(name ='Underwear', category = 'Clothing', essential = True, rain_precautionary = False, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
RainCoat = Item(name ='Rain Coat', category = 'Clothing', essential = False, rain_precautionary = True, cold_precautionary = False, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)
ThermalLayer = Item(name ='Thermal Layer', category = 'Clothing', essential = False, rain_precautionary = False, cold_precautionary = True, heat_precautionary = False, emergency_precautionary = False, created_by = 1, removable =False)


db.session.add(Maps)
db.session.add(Permits)
db.session.add(Compass)
db.session.add(Backpack)
db.session.add(RainCover)
db.session.add(Tent)
db.session.add(Tarp)
db.session.add(RainFly)
db.session.add(SleepingBag)
db.session.add(SleepingPad)
db.session.add(TrekkingPoles)
db.session.add(BearCanister)
db.session.add(WaterFilter)
db.session.add(Aquatabs)
db.session.add(HeadLamp)
db.session.add(ExtraBatteries)
db.session.add(BearSpray)
db.session.add(BugSpray)
db.session.add(Knife)
db.session.add(MultiTool)
db.session.add(Nalgene)
db.session.add(HandSanitizer)
db.session.add(ToiletPaper)
db.session.add(SealableBags)
db.session.add(Toothbrush)
db.session.add(Toolpaste)
db.session.add(Soap)
db.session.add(ContactSolution)
db.session.add(Deodorant)
db.session.add(BathroomHandShovel)
db.session.add(Food)
db.session.add(EnergyChews)
db.session.add(Fuel)
db.session.add(Matches)
db.session.add(FireStarter)
db.session.add(FlintSteel)
db.session.add(Lint)
db.session.add(Lighter)
db.session.add(Stove)
db.session.add(Cookset)
db.session.add(PotGrabber)
db.session.add(Bowls)
db.session.add(Plates)
db.session.add(Silverware)
db.session.add(Mugs)
db.session.add(DishSoap)
db.session.add(FirstAidKit)
db.session.add(Garmin)
db.session.add(WalkieTalkies)
db.session.add(Gauze)
db.session.add(Wraps)
db.session.add(Flashlight)
db.session.add(String)
db.session.add(Rope)
db.session.add(ReadingMaterial)
db.session.add(PortablePhoneCharger)
db.session.add(Hatchet)
db.session.add(SmallTrashBags)
db.session.add(TentPatchKit)
db.session.add(DuctTape)
db.session.add(SleepingBagLiner)
db.session.add(InflatablePillow)
db.session.add(BugNet)
db.session.add(PlayingCards)
db.session.add(PetPack)
db.session.add(PetFood)
db.session.add(Treats)
db.session.add(LongLeash)
db.session.add(ShortLeash)
db.session.add(Harness)
db.session.add(Comb)
db.session.add(AbrasionSpray)
db.session.add(CollapsibleBowl)
db.session.add(LightCollar)
db.session.add(Towel)
db.session.add(PetSleepingPad)
db.session.add(PoopBags)
db.session.add(HandWarmers)
db.session.add(FeetWarmers)
db.session.add(MetalNalgene)
db.session.add(Gloves)
db.session.add(Hat)
db.session.add(LongSleeveShirt)
db.session.add(QuickDryingPants)
db.session.add(RainProofPants)
db.session.add(Shorts)
db.session.add(Leggings)
db.session.add(LightweightFleece)
db.session.add(LightweightJacket)
db.session.add(WoolSocks)
db.session.add(HikingBoots)
db.session.add(CampSandals)
db.session.add(MoistureWickingShirt)
db.session.add(Underwear)
db.session.add(RainCoat)
db.session.add(ThermalLayer)
db.session.commit()