INSERT INTO items (name, category, essential, rain_precautionary, cold_precautionary, heat_precautionary, emergency_precautionary, removable)
VALUES
('Maps', 'Navigation', True, False, False, False, True, False),
('Permits', 'Navigation', True, False, False, False, False, False),
('Compass', 'Navigation', True, False, False, False, True, False),
('Backpack', 'Gear', True, False, False, False, False, False),
('Rain Cover', 'Gear', True, True, False, False, False, False),
('Tent', 'Gear', True, False, False, False, False, False),
('Tarp', 'Gear', True, False, False, False, False, False),
('Rain Fly', 'Gear', True, True, False, False, False, False),
('Sleeping Bags', 'Sleeping', True, False, False, False, False, False),
('Sleeping Pad', 'Sleeping', True, False, False, False, False, False),
('Trekking Poles', 'Gear', True, False, False, False, False, False),
('Bear Canister', 'Safety', True, False, False, False, False, False),
('Water Filter/Purifier','Safety', True, False, False, True, True, False),
('Aquatabs', 'Safety', True, False, False, False, True, False),
('Head Lamp', 'Safety', True, False, False, False, True, False),
('Extra Batteries', 'Miscellaneous', True, False, False, False, False, False),
('Bear Spray', 'Safety', True, False, False, False, False, False),
('Bug Spray', 'Miscellaneous', True, False, False, False, False, False),
('Knife', 'Miscellaneous', False, False, False, False, True, False),
('Multi-Tool', 'Miscellaneous', False, False, False, False, True, False),
('Nalgene', 'Gear', True, False, False, False, False, False),
('Hand Sanitizer', 'Hygiene', False, False, False, False, False, False),
('Toilet Paper ', 'Hygiene', True, False, False, False, False, False),
('Sealable Bags', 'Hygiene', True, False, False, False, False, False),
('Toothbrush', 'Hygiene', False, False, False, False, False, False),
('Toolpaste', 'Hygiene', False, False, False, False, False, False),
('Soap', 'Hygiene', False, False, False, False, False, False),
('Contact Solution', 'Hygiene', False, False, False, False, False, False),
('Deodorant', 'Hygiene', False, False, False, False, False, False),
('Bathroom Hand Shovel', 'Hygiene', False, False, False, False, False, False),
('Food', 'Cooking', True, False, False, False, False, False),
('Energy Chews', 'Cooking', False, False, False, False, False, False),
('Fuel', 'Cooking', True, False, False, False, False, False),
('Matches', 'Cooking', False, False, True, False, False, False),
('Fire Starter', 'Cooking', False, True, False, False, False, False),
('Flint and Steel', 'Cooking', False, False, False, False, True, False),
('Lint', 'Cooking', False, True, False, False, False, False),
('Lighter', 'Cooking', False, False, False, False, False, False),
('Stove', 'Cooking', True, False, False, False, False, False),
('Cookset', 'Cooking', True, False, False, False, False, False),
('Pot Grabber', 'Cooking', False, False, False, False, False, False),
('Bowls', 'Cooking', False, False, False, False, False, False),
('Plates', 'Cooking', False, False, False, False, False, False),
('Silverware', 'Cooking', False, False, False, False, False, False),
('Mugs', 'Cooking', False, False, False, False, False, False),
('Dish Soap', 'Cooking', False, False, False, False, False, False),
('First-Aid Kit', 'Safety', True, False, False, False, True, False),
('Garmin', 'Safety', False, False, False, False, True, False),
('Walkie Talkies', 'Safety', False, False, False, False, True, False),
('Gauze', 'Safety', False, False, False, False, True, False),
('Wraps', 'Safety', False, False, False, False, True, False),
('Flashlight', 'Safety', False, False, False, False, True, False),
('String', 'Miscellaneous', False, False, False, False, False, False),
('Rope', 'Miscellaneous', False, False, False, False, False, False),
('Reading Material', 'Miscellaneous', False, False, False, False, False, False),
('Portable Phone Charger', 'Miscellaneous', False, False, False, False, False, False),
('Hatchet', 'Miscellaneous', False, False, False, False, False, False),
('Small Trash Bags', 'Miscellaneous', False, False, False, False, False, False),
('Tent Patch Kit', 'Miscellaneous', False, False, False, False, False, False),
('Duct Tape', 'Miscellaneous', False, False, False, False, False, False),
('Sleeping Bag Liner', 'Sleeping', False, False, True, False, False, False),
('Inflatable Pillow', 'Sleeping', False, False, False, False, False, False),
('Bug Net', 'Miscellaneous', False, False, False, False, False, False),
('Playing Cards', 'Miscellaneous', False, False, False, False, False, False),
('Pet Pack', 'Pet', False, False, False, False, False, False),
('Pet Food', 'Pet', False, False, False, False, False, False),
('Treats', 'Pet', False, False, False, False, False, False),
('Long Leash', 'Pet', False, False, False, False, False, False),
('Short Leash', 'Pet', False, False, False, False, False, False),
('Harness', 'Pet', False, False, False, False, False, False),
('Comb', 'Pet', False, False, False, False, False, False),
('Abrasion Spray', 'Pet', False, False, False, False, False, False),
('Collapsible Bowl', 'Pet', False, False, False, False, False, False),
('Light Collar', 'Pet', False, False, False, False, False, False),
('Towel', 'Pet', False, False, False, False, False, False),
('Pet Sleeping Pad', 'Pet', False, False, False, False, False, False),
('Poop Bags', 'Pet', False, False, False, False, False, False),
('Hand Warmers', 'Miscellaneous', False, False, True, False, True, False),
('Feet Warmers', 'Miscellaneous', False, False, True, False, True, False),
('Metal Nalgene', 'Gear', False, False, True, False, False, False),
('Gloves', 'Clothing', False, False, True, False, False, False),
('Hat', 'Clothing', False, False, True, False, False, False),
('Long Sleeve Shirt', 'Clothing', False, False, True, False, False, False),
('Quick Drying Pants', 'Clothing', True, True, False, False, False, False),
('Rain Proof Pants', 'Clothing', True, True, False, False, False, False),
('Shorts', 'Clothing', False, False, False, True, False, False),
('Leggings', 'Clothing', False, False, False, True, False, False),
('Lightweight Fleece', 'Clothing', False, False, False, False, False, False),
('Lightweight Jacket', 'Clothing', False, False, False, True, False, False),
('Wool Socks', 'Clothing', True, False, True, False, False, False),
('Hiking Boots', 'Clothing', True, False, False, False, False, False),
('Camp Sandals', 'Clothing', False, False, False, False, False, False),
('Moisture Wicking Shirt', 'Clothing', True, True, False, False, False, False),
('Underwear', 'Clothing', True, False, False, False, False, False),
('Rain Coat', 'Clothing', False, True, False, False, False, False),
('Thermal Layer', 'Clothing', False, False, True, False, False, False);